### PR TITLE
Added links to the table of possible heeliesButton values

### PR DESCRIPTION
**Pull request by semism**
I found it hard to find the name of the **_LeftStick_** (clicking the left analog stick).
So I opened up the code to see what it uses to parse them then ended up the the Microsoft Docs for the names of each Button.

I ran the game with some values looks like the links are reliable.

Chose to include links vs just embedding them in the README to keep readme shorter, and in case of changes (unlikely). 
If you'd prefer having it embedded lmk and I'll gladly do it that way.

🤞🏽pls also include in nexusmods.

### CODE REVIEW

**Comment by fakemonster** [comment]
love it, thank you! wondering what you think about using the [stardew wiki](https://stardewvalleywiki.com/Modding:Player_Guide/Key_Bindings) for this instead (we get both in one link, plus it stays "in universe")

whatever we go with here, i'll update in nexusmods as well

**Comment by semism** [comment]
The wiki link seems to be much better. Didn’t know it covered keybindings. I’ll put that in today. Thank you!

**Comment by semism** [comment]
@fakemonster Hello there, turns out that today took a month but here it is. Please check my new commit. Cheers 🍻

**Comment by fakemonster** [comment]
Thanks @semism! I'll go ahead and update nexusmods as well

**Pull request merged**
